---
- name: checking package for update
  script: /etc/ansible/roles/windows_facts/files/windows_facts.ps1
  register: local_facts

- raw: "(Invoke-WebRequest -Uri http://169.254.169.254/latest/meta-data/instance-id/).Content"
  register: instance_id
  when: ec2_id is not defined

- set_fact:
    ec2_id="{{ instance_id.stdout_lines[0] }}"
  when: ec2_id is not defined

- set_fact:
    all_pack="{{ local_facts.stdout_lines[0] }}"
    sec_pack="{{ local_facts.stdout_lines[1] }}"
    ansible_password="********"

- name: dump facts to file
  local_action: copy content='{{ hostvars[inventory_hostname] | to_nice_json}}' dest="/tmp/{{ ec2_id }}.json"

- name: remove unnecessary fields
  local_action: command /usr/local/pre_s3.py /tmp/{{ ec2_id }}.json

- name: upload facts into s3
  local_action: s3 bucket={{ s3_bucket }} object=/ansible-facts/{{ ec2_id }}.json src="/tmp/{{ ec2_id }}.json" mode=put overwrite=True
