---
- hosts: tag_Name_ansible_server
  become: yes
  vars:
    cron_user: root
    s3_bucket: some-bucket

  pre_tasks:
  - name: ensure cloudaware_repos directory exists
    file: path=/etc/ansible/cloudaware_repos recurse=yes state=directory mode=0755

  - name: clone cloudaware repository
    local_action: git
                  repo=https://github.com/cloudaware/public-utilities.git
                  dest=/etc/ansible/cloudaware_repos
                  force=yes

  - name: copy files to /usr directory
    local_action: copy src=/etc/ansible/cloudaware_repos/ansible-to-s3/usr dest=/

  - name: copy files to /etc directory
    local_action: copy src=/etc/ansible/cloudaware_repos/ansible-to-s3/etc dest=/

  - name: copy main file
    local_action: copy src=/etc/ansible/cloudaware_repos/ansible-to-s3/main.yml dest=/etc/ansible

  - name: copy new facts_to_s3.yml file
    local_action: src=/etc/ansible/cloudaware_repos/ansible-to-s3/facts_to_s3.yml dest=/etc/ansible

  - name: check attributes for custom  facts files
    local_action: file path=/etc/ansible/facts.d/upgr_pack.fact  mode=0755

  - name: check attributes for pre_s3.py file
    local_action: file path=/usr/local/pre_s3.py  mode=0755

  - include: main.yml

  post_tasks:
  - name: create cron job
    local_action: template src=templates/ansible_to_s3.j2 dest=/etc/cron.d/ansible_to_s3 mode=0644
